version: "3.7"

services:
    app1:
        image: simple-app
        build: ./spring-boot-simple
        ports:
            - "8081:8080"
            
    app2:
        image: simple-app
        build: ./spring-boot-simple
        ports:
            - "8082:8080"            

    nginx:
        build:
            context: ./nginx
            dockerfile: dockerfile_round_robin
        depends_on:
            - app1
        ports:
            - "8080:80"
